name: NodeJS with Webpack

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x ## ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x ## ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build --if-present
    - name: Zip artifact for deployment
      run: zip release.zip ./**/* -r
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: release.zip
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    # - name: Display structure of downloaded files
    #   run: ls -R
    - name: Deploy to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        source: "."
        target: "/home/snplus-vm-admin/project1"
    - name: Post Deploy Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        timeout: 30s
        script: |
          cd project1/
          unzip release.zip
          ls -l
          cd build/
          pwd
          ls -l
        
